--- #YAML:1.0
name:               Protocol-XMLRPC
version:            0.08
abstract:           Asynchronous, web framework agnostic XML-RPC implementation
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Base64:  0
    Test::More:    0
    XML::LibXML:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
